### ISSUE TITLE
How can i break the line after text 

### ISSUE THREAD

**Issue by azartheen** [Rishit-dagli/Whatsapp-mass-messaging-Python#2]
i mention text msg like

**hi automation

this is demo**

i add these line but the msg will be sent by 2
 
how can i send these text format i try by basic thing "%0A%0A" but its now work

**Comment by Rishit-dagli** [comment]
You can use the `\n` to specify linebreaks. I am closing this issue as of now but feel free to comment if you are face issues with this.
